const {Guest, Book, Host, Comment, AboutYou, Genre, SocialMedia, AboutHost} = require('.')

Book.belongsTo(Guest); 
Book.belongsTo(Host)
Comment.belongsTo(Guest)
Comment.belongsTo(Host)
Comment.belongsTo(Book, {onDelete: 'CASCADE'})
AboutYou.belongsTo(Guest)
Genre.belongsTo(Guest)
SocialMedia.belongsTo(Guest)
AboutHost.belongsTo(Host)
Guest.hasMany(Book, {as: 'books'})
Host.hasMany(Book, {as:'hostBooks'})
Guest.hasMany(Comment, {as: 'comments'})
Host.hasMany(Comment, {as: 'hostComments'})
Book.hasMany(Comment, {as: 'bookComments'})
Host.hasOne(AboutHost)
Guest.hasOne(AboutYou)
Guest.hasOne(Genre)
Guest.hasOne(SocialMedia)